package com.example.jrpricing.domain.price

import com.example.jrpricing.domain.core.*
import com.example.jrpricing.domain.core.Destination.HIMEJI
import com.example.jrpricing.domain.core.Destination.SHINOSAKA
import com.example.jrpricing.domain.core.SeatType.FREE
import com.example.jrpricing.domain.core.SeatType.RESERVED
import com.example.jrpricing.domain.core.TrainType.HIKARI
import com.example.jrpricing.domain.core.TrainType.NOZOMI
import com.example.jrpricing.domain.core.TripType.ONE_WAY
import com.example.jrpricing.domain.core.TripType.ROUND_TRIP
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.Arguments
import org.junit.jupiter.params.provider.Arguments.arguments
import org.junit.jupiter.params.provider.MethodSource
import java.util.stream.Stream

internal class PriceCalculationServiceTest {

    @ParameterizedTest
    @MethodSource("dataProvider")
    fun calculate(
        destination: Destination,
        trainType: TrainType,
        seatType: SeatType,
        passengers: Passengers,
        departureDate: DepartureDate,
        tripType: TripType,
        expected: Price
    ) {
        val service = PriceCalculationService(
            destination,
            trainType,
            seatType,
            passengers,
            departureDate,
            tripType
        )

        val price = service.calculate()

        assertEquals(expected, price)
    }

    companion object {
        @Suppress("unused")
        @JvmStatic
        fun dataProvider(): Stream<Arguments> = Stream.of(
            arguments(
                SHINOSAKA,
                NOZOMI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(14190)
            ),
            arguments(
                SHINOSAKA,
                NOZOMI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(28380)
            ),
            arguments(
                SHINOSAKA,
                NOZOMI,
                FREE,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(7090)
            ),
            arguments(
                SHINOSAKA,
                NOZOMI,
                FREE,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(14180)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(13870)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(27740)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                FREE,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(6930)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                FREE,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(13860)
            ),
            arguments(
                SHINOSAKA,
                NOZOMI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(14720)
            ),
            arguments(
                SHINOSAKA,
                NOZOMI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(29440)
            ),
            arguments(
                SHINOSAKA,
                NOZOMI,
                RESERVED,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(7360)
            ),
            arguments(
                SHINOSAKA,
                NOZOMI,
                RESERVED,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(14720)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(14400)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(28800)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(7200)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(14400)
            ),
            arguments(
                HIMEJI,
                NOZOMI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(15930)
            ),
            arguments(
                HIMEJI,
                NOZOMI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(29840)
            ),
            arguments(
                HIMEJI,
                NOZOMI,
                FREE,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(7960)
            ),
            arguments(
                HIMEJI,
                NOZOMI,
                FREE,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(14920)
            ),
            arguments(
                HIMEJI,
                HIKARI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(15400)
            ),
            arguments(
                HIMEJI,
                HIKARI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(28780)
            ),
            arguments(
                HIMEJI,
                HIKARI,
                FREE,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(7700)
            ),
            arguments(
                HIMEJI,
                HIKARI,
                FREE,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(14380)
            ),
            arguments(
                HIMEJI,
                NOZOMI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(16460)
            ),
            arguments(
                HIMEJI,
                NOZOMI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(30900)
            ),
            arguments(
                HIMEJI,
                NOZOMI,
                RESERVED,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(8230)
            ),
            arguments(
                HIMEJI,
                NOZOMI,
                RESERVED,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(15440)
            ),
            arguments(
                HIMEJI,
                HIKARI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(15930)
            ),
            arguments(
                HIMEJI,
                HIKARI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(29840)
            ),
            arguments(
                HIMEJI,
                HIKARI,
                RESERVED,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(7960)
            ),
            arguments(
                HIMEJI,
                HIKARI,
                RESERVED,
                FixturePassengers().aChild(),
                FixtureDepartureDate().get(),
                ROUND_TRIP,
                Price(14920)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().peakStart(),
                ONE_WAY,
                Price(14600)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().peakEnd(),
                ONE_WAY,
                Price(14600)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().peakOffStart(),
                ONE_WAY,
                Price(14200)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().peakOffEnd(),
                ONE_WAY,
                Price(14200)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().peakStart(),
                ONE_WAY,
                Price(13870)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                FREE,
                FixturePassengers().anAdult(),
                FixtureDepartureDate().peakOffStart(),
                ONE_WAY,
                Price(13870)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().smallGroup(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(67240)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().smallGroup(),
                FixtureDepartureDate().smallGroupDiscountStart(),
                ONE_WAY,
                Price(71200)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().smallGroup(),
                FixtureDepartureDate().smallGroupDiscountEnd(),
                ONE_WAY,
                Price(72190)
            ),
            arguments(
                SHINOSAKA,
                HIKARI,
                RESERVED,
                FixturePassengers().tooLargeGroup(),
                FixtureDepartureDate().get(),
                ONE_WAY,
                Price(904280)
            )
        )
    }
}
